Fix doc build error
This fixes the following error in the doc job.

```
TypeError: not all arguments converted during string formatting
```

Change-Id: If67f629dfd6b07ed198155bec43a128369b7affa
(cherry picked from commit 989f559d739e67b03ee0f8d324c5ac26266fbbb9)